<?php

namespace EphyBundle\Repository;

/**
 * EphySubstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphySubstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
