<?php

namespace EphyBundle\Repository;

/**
 * EphyUsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphyUsageRepository extends \Doctrine\ORM\EntityRepository
{
}
