# app/config/security.yml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # ...

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true

    role_hierarchy:
        ROLE_LEMCA: ROLE_USER
        ROLE_ADMIN: ROLE_LEMCA

    access_control:
        - { path: ^/init$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/k8f96gtb$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/annonces/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
