# app/config/security.yml
security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # ...

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                enable_csrf: true

            logout:       true

    role_hierarchy:
        ROLE_LEMCA: ROLE_USER
        ROLE_ADMIN: ROLE_LEMCA

    access_control:
        - { path: ^/init$, role: PUBLIC_ACCESS }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/register, role: PUBLIC_ACCESS }
        - { path: ^/resetting, role: PUBLIC_ACCESS }
        - { path: ^/k8f96gtb$, role: PUBLIC_ACCESS }
        - { path: ^/annonces/api, role: PUBLIC_ACCESS }
