<?php

namespace AgriBundle\Repository;

/**
 * AchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatRepository extends \Doctrine\ORM\EntityRepository
{
    function add($achat){
        $em = $this->getEntityManager();
        $produit = $em->getRepository('AgriBundle:Produit')->findOrCreate($achat->name, $achat->type);
        $achat->produit = $produit;
        $em->persist($achat);
        $em->flush();
        $em->getRepository('AgriBundle:Produit')->update($produit);
    }
}
