<?php

namespace AgriBundle\Repository;

/**
 * CampagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagneRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllforCompany($company){
        $query = $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->setParameter('company', $company)
            ->getQuery();

        return $query->getResult();
    }
}
