<?php

namespace AgriBundle\Repository;
use AgriBundle\Entity\Campagne;

/**
 * CampagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagneRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllforCompany($company){
        $query = $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->setParameter('company', $company)
            ->getQuery();

        return $query->getResult();
    }

     function findFirstOrCreate($company, $name){
         $em = $this->getEntityManager();
         $campagne = $this->findOneByCompany($company);
         if($campagne){
             return $campagne;
         }
         $campagne = new Campagne();
         $campagne->name = $name;
         $campagne->company = $company;
         $em->persist($campagne);
         $em->flush();
         return $campagne;
     }
}
