<?php

namespace AgriBundle\Repository;
use AgriBundle\Entity\Company;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForUser($user){
        $em = $this->getEntityManager();
        $companies = $this->createQueryBuilder('c')
            ->innerJoin('c.users', 'u')
            ->where('u.id = :user_id')
            ->setParameter('user_id', $user->id)
            ->getQuery()->getResult();
        return $companies;
    }

    function findOrCreate($user){
        $em = $this->getEntityManager();
        $companies = $this->getAllForUser($user);
        if(count($companies)>0){
            return $companies[0];
        }
        $company = new Company();
        $company->users = [$user];
        $company->name = $user->getUserName();
        $company->adresse = "";
        $em->persist($company);
        $em->flush();
        return $company;
    }
}
