<?php

namespace AgriBundle\Repository;
use AgriBundle\Entity\Company;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    function findOrCreate($user){
        $em = $this->getEntityManager();
        $company = $this->findOneByUser($user);
        if($company){
            return $company;
        }
        $company = new Company();
        $company->user = $user;
        $company->name = "";
        $company->adresse = "";
        $em->persist($company);
        $em->flush();
        return $company;
    }
}
