<?php

namespace AgriBundle\Repository;

/**
 * DeplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeplacementRepository extends \Doctrine\ORM\EntityRepository
{
    function save($gasoil){
        $em = $this->getEntityManager();
        $em->persist($gasoil);
        $em->flush();
        return $gasoil;

    }

    function getAllforCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->setParameter('campagne', $campagne)
            ->orderBy('p.date' , 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
