<?php

namespace AgriBundle\Repository;
use AgriBundle\Entity\EphyProduit;

/**
 * EphyProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphyProduitRepository extends \Doctrine\ORM\EntityRepository
{
    function addRows($rows){
        $ephyproduit = new EphyProduit();
        $ephyproduit->amm = $rows[1];
        $ephyproduit->name = $rows[2];
        $ephyproduit->completeName = $ephyproduit->amm . ' - ' . $ephyproduit->name;
        $produit_count = $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->where('p.completeName = :completeName')
            ->setParameter('completeName', $ephyproduit->completeName)
            ->getQuery()
            ->getSingleScalarResult();
        if($produit_count == 0){
            print json_encode($ephyproduit );
            $em = $this->getEntityManager();
            $em->persist($ephyproduit);
            $em->flush();
        }
        return $ephyproduit;
    }
}
