<?php

namespace AgriBundle\Repository;

/**
 * EphySubstanceProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphySubstanceProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
