<?php

namespace AgriBundle\Repository;

/**
 * GasoilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GasoilRepository extends \Doctrine\ORM\EntityRepository
{
    function save($gasoil){
        $em = $this->getEntityManager();
        $em->persist($gasoil);
        $em->flush();
        return $gasoil;

    }

    function getAllforCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->setParameter('campagne', $campagne)
            ->orderBy('p.date' , 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    function getAllforCompanyGroupByType($company){
        $query = $this->createQueryBuilder('p')
            ->addSelect('p.type AS type')
            ->addSelect('SUM(p.litre) AS sum_litre')
            ->groupBy('p.type')
            ->getQuery();

        return $query->getResult();
    }

    function getAllForCompany($company){
        $query = $this->createQueryBuilder('p')
            ->join('p.campagne', 'c')
            ->where('c.company = :company')
            ->setParameter('company', $company)
            ->orderBy('p.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
