<?php

namespace AgriBundle\Repository;

/**
 * IlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IlotRepository extends \Doctrine\ORM\EntityRepository
{
}
