<?php

namespace AgriBundle\Repository;

/**
 * InterventionProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionProduitRepository extends \Doctrine\ORM\EntityRepository
{
    function save($intervention_produit){
        $em = $this->getEntityManager();
        $produit = $em->getRepository('AgriBundle:Produit')->findOneByName($intervention_produit->name);
        $intervention_produit->produit = $produit;
        $em->persist($intervention_produit);
        $em->flush();
        $produit = $em->getRepository('AgriBundle:Produit')->update($produit);
        return $produit;
    }

    function getGroupByProduct(){
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("SELECT * FROM intervention_produit p group by p.produit_no_ephy");
        $statement->execute();
        $results = $statement->fetchAll();
        return $results;
    }
}

