<?php

namespace AgriBundle\Repository;
use AgriBundle\Entity\Intervention;
use AgriBundle\Entity\InterventionParcelle;
use \DateTime;


/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    function add($type, $date, $parcelles){
        $em = $this->getEntityManager();
        $intervention = new Intervention();
        $intervention->type = $type;
        $intervention->date = new Datetime($date);
        $em->persist($intervention);
        foreach($parcelles as $p){
            $it = new InterventionParcelle();
            $it->intervention = $intervention;
            $it->parcelle = $p;
            $em->persist($it);
            //$intervention->parcelles[] = $it;
        }
        $em->flush();
        return $intervention;
    }

    function getAll(){
        return $this->findAll();
    }
}
