<?php

namespace AgriBundle\Repository;

/**
 * InterventionProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionProduitRepository extends \Doctrine\ORM\EntityRepository
{
    function save($intervention_produit){
        $em = $this->getEntityManager();
        $produit = $em->getRepository('AgriBundle:Produit')->findOneByCompleteName($intervention_produit->name);
        $intervention_produit->produit = $produit;
        $em->persist($intervention_produit);
        $em->flush();
        return $produit;
    }
}
