<?php

namespace AgriBundle\Repository;
use AgriBundle\Entity\Intervention;
use AgriBundle\Entity\InterventionParcelle;
use \DateTime;


/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    function add($type, $date, $parcelles){
        $em = $this->getEntityManager();
        $intervention = new Intervention();
        $intervention->type = $type;
        $intervention->date = new Datetime($date);
        $em->persist($intervention);
        foreach($parcelles as $p){
            $it = new InterventionParcelle();
            $it->intervention = $intervention;
            $it->parcelle = $p;
            $em->persist($it);
            //$intervention->parcelles[] = $it;
        }
        $em->flush();
        return $intervention;
    }

    function delete($intervention_id){
        $em = $this->getEntityManager();
        $intervention = $em->getRepository('AgriBundle:Intervention')->findOneById($intervention_id);
        $intervention_parcelles = $em->getRepository('AgriBundle:InterventionParcelle')
                                   ->findBy(array('intervention'=>$intervention));
        $intervention_produits = $em->getRepository('AgriBundle:InterventionProduit')
                                   ->findBy(array('intervention'=>$intervention));
        foreach ($intervention_produits as $it) {
            $em->getRepository('AgriBundle:InterventionProduit')->delete($it->id);
        }
        foreach ($intervention_parcelles as $it) {
            $em->remove($it);
        }
        $em->remove($intervention);
        $em->flush();
    }

    function getAllForCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->join('p.parcelles', 'parcelle_it')
            ->addSelect('parcelle_it')
            ->join('p.produits', 'produit_it')
            ->addSelect('produit_it')
            ->join('produit_it.produit', 'produit2')
            ->addSelect('produit2')
            ->setParameter('campagne', $campagne)
            ->orderBy('p.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    function getAllForCompany($company){
        $query = $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->setParameter('company', $company)
            ->orderBy('p.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }


    function getAllForParcelle($parcelle){
        $em = $this->getEntityManager();
        $sql = 'SELECT intervention_id FROM intervention_parcelle where parcelle_id = ?';

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->bindValue(1, $parcelle->id);
        $statement->execute();
        $parcelles = $statement->fetchAll();
        $ids = [];
        foreach($parcelles as $p){
            $ids[] = $p["intervention_id"];

        }

        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $this->createQueryBuilder('p')
            ->where('p.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->orderBy('p.date', 'DESC')
            ->getQuery();

            return $query->getResult();
    }

    function getAllForProduit($produit){
        $em = $this->getEntityManager();
        $sql = 'SELECT intervention_id FROM intervention_produit where produit_id = ?';

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->bindValue(1, $produit->id);
        $statement->execute();
        $produits = $statement->fetchAll();
        $ids = [];
        foreach($produits as $p){
            $ids[] = $p["intervention_id"];

        }

        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $this->createQueryBuilder('p')
            ->where('p.id IN (:ids)')
             ->setParameter('ids', $ids)
             ->orderBy('p.date', 'DESC')
             ->getQuery();

             return $query->getResult();
    }

    function getAllForMateriel($materiel){
        $em = $this->getEntityManager();
        $sql = 'SELECT intervention_id FROM intervention_materiel where materiel_id = ?';

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->bindValue(1, $materiel->id);
        $statement->execute();
        $produits = $statement->fetchAll();
        $ids = [];
        foreach($produits as $p){
            $ids[] = $p["intervention_id"];
        }

        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $this->createQueryBuilder('p')
            ->where('p.id IN (:ids)')
             ->setParameter('ids', $ids)
             ->orderBy('p.date', 'DESC')
             ->getQuery();

             return $query->getResult();
    }
}
