<?php

namespace AgriBundle\Repository;

/**
 * InterventionParcelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionParcelleRepository extends \Doctrine\ORM\EntityRepository
{
    function save($intervention_parcelle){
        $em = $this->getEntityManager();
        $em->persist($intervention_parcelle);
        $em->flush();
        $intervention = $em->getRepository('AgriBundle:Intervention')->findOneById($intervention_parcelle->intervention->id);
        $intervention->surface = 0;
        foreach($intervention->parcelles as $p){
            $intervention->surface += $p->parcelle->surface;
        }
        $em->persist($intervention);
        $em->flush();
        return $intervention;
    }
}
