<?php

namespace AgriBundle\Repository;

/**
 * InterventionParcelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionParcelleRepository extends \Doctrine\ORM\EntityRepository
{
}
