<?php

namespace AgriBundle\Repository;

/**
 * InterventionProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
