<?php

namespace AgriBundle\Repository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            //->where('p.campagne = :campagne')
            //->leftJoin('p.ilot', 'i')
            //->setParameter('campagne', $campagne)
            ->addorderBy('p.name', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
