<?php

namespace AgriBundle\Repository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->setParameter('campagne', $campagne)
            ->addorderBy('p.name', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    function getSumForParcelle($parcelle){
        $res = $this->createQueryBuilder('p')
            ->andWhere('p.parcelle = :parcelle')
            ->setParameter('parcelle', $parcelle)
            ->select('SUM(p.poid_norme) as poid_norme')
            ->getQuery()
            ->getOneOrNullResult();

        return $res['poid_norme'];
    }
}
