<?php

namespace AgriBundle\Repository;

/**
 * MaterielInterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielInterventionRepository extends \Doctrine\ORM\EntityRepository
{
}
