<?php

namespace AgriBundle\Repository;
use AgriBundle\Entity\Parcelle;

/**
 * ParcelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelleRepository extends \Doctrine\ORM\EntityRepository
{
    function add($ilot_id, $campagne, $name, $culture, $surface){
        $em = $this->getEntityManager();
        $ilot = $em->getRepository('AgriBundle:Ilot')->getById($ilot_id);
        $parcelle = new Parcelle();
        $parcelle->ilot = $ilot;
        $parcelle->name = $name;
        $parcelle->culture = $culture;
        $parcelle->campagne= $campagne;
        $parcelle->surface = $surface;
        $em->persist($parcelle);
        $em->flush();
        return $parcelle;
    }
    
    function getAllForCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->setParameter('campagne', $campagne)
            ->getQuery();

        return $query->getResult();
    }

    function getAllForAdherent($adherentId){
        $query = $this->createQueryBuilder('p')
            ->where('p.adherent = :adherent')
            ->setParameter('adherent', $adherentId)
            ->getQuery();

        return $query->getResult();
    }

}
