<?php

namespace App\Repository\Gestion;

/**
 * CommercialisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercialisationRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->setParameter('campagne', $campagne)
            ->addorderBy('p.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
