<?php

namespace GestionBundle\Repository;

/**
 * AppartementOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppartementOperationRepository extends \Doctrine\ORM\EntityRepository
{
    function getAll(){
        return $this->createQueryBuilder('p')
            ->orderBy('p.date')
            ->getQuery()->getResult();
    }
}
