<?php

namespace GestionBundle\Repository;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForCampagne($campagne){
            return $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->orderBy('p.name')
            ->setParameter('company', $campagne->company)
            ->getQuery()->getResult();
    }
}
