<?php

namespace GestionBundle\Repository;

use Datetime;
use GestionBundle\Entity\Cours;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{
    function saveArray($company, $array){
        $date = Datetime::createFromFormat("d-m-Y", $array["date"]);
        foreach($array as $key => $value){
            if($key != "date"){
                $this->save($company, $date, $key, $value);
            }
        }

    }

    function save($company, $date, $produit, $value){
        $values = explode("_", $produit);
        $em = $this->getEntityManager();

        $cours = new Cours();
        $cours->campagne = $em->getRepository('AgriBundle:Campagne')->findOrCreate($company, $values[0]);
        $cours->date = $date;
        $cours->value = $value;
        $cours->produit = $values[1];


        $em->persist($cours);
        $em->flush();
    }

    function getAllForCampagne($campagne){
            return $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->orderBy('p.date', 'DESC')
            ->setParameter('campagne', $campagne)
            ->getQuery()->getResult();
    }
}
