<?php

namespace GestionBundle\Repository;

/**
 * EcritureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcritureRepository extends \Doctrine\ORM\EntityRepository
{
}
