<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Group;

/**
 * AchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
    function count($group){
        $em = $this->getEntityManager();
        $campagne = $em->getRepository('AgriBundle:Campagne')->findOneById("f49d37d6-3951-11e7-92c4-80e65014bb7c");

        $achats = $this->findByCampagne($campagne);
        foreach ($achats as $achat) {
            $em->remove($achat);
        }
        $em->flush();

        if (($handle = fopen($fileName, "r")) !== FALSE) {
            $i = 0;
            while (($rows = fgetcsv($handle, null, ";")) !== FALSE) {
                //if ($i == 0) { $i = 1;continue; }
                $this->addRows($rows, $campagne);
            }
        }
    }

    function getAllForProduit($produit){
        $query = $this->createQueryBuilder('p')
            ->where('p.produit = :produit')
            ->setParameter('produit', $produit)
            ->orderBy('p.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    function delete($achat_id){
        $em = $this->getEntityManager();
        $achat = $this->findOneById($achat_id);
        $em->remove($achat);
        $em->flush();
    }
}
