<?php

namespace AppBundle\Repository;

/**
 * InterventionParcelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionParcelleRepository extends \Doctrine\ORM\EntityRepository
{
    function save($intervention_parcelle){
        $em = $this->getEntityManager();
        $em->persist($intervention_parcelle);
        $em->flush();
        $em->getRepository('AppBundle:Intervention')->updateSurface($intervention_parcelle->intervention->id);
    }
}
