<?php

namespace AppBundle\Repository;

/**
 * MaterielEntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielEntretienRepository extends \Doctrine\ORM\EntityRepository
{
}
