<?php

namespace AppBundle\Repository;

/**
 * AchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsersContainGroup($group){
        $em = $this->getEntityManager();
        $repository = $em->getRepository('AppBundle:User');
        $users = $repository->createQueryBuilder('u')
            ->innerJoin('u.groups', 'g')
            ->where('g.id = :group_id')
            ->setParameter('group_id', $group->id)
            ->getQuery()->getResult();
        return $users;
    }
}
