gestion:
    resource: "@GestionBundle/Controller/"
    type:     annotation
    prefix:   /

ephy:
    resource: "@EphyBundle/Controller/"
    type:     annotation
    prefix:   /

agri:
    resource: "@AgriBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


login_check:
    path: /login_check


logout:
    path: /logout
