# app/config/security.yml
security:
    encoders:
        AgriBundle\Entity\User:
            algorithm: bcrypt

    # ...

    providers:
        our_db_provider:
            entity:
                class: AgriBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        no_login:
            pattern: ^/bk8f96gt$
            anonymous: true

        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu

        main:
            pattern:      ^/
            anonymous:    false
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /
            provider: our_db_provider
