<?php

namespace App\Repository;

/**
 * AnalyseSolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyseSolRepository extends \Doctrine\ORM\EntityRepository
{
}
