<?php

namespace App\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    function getAll(){
        $query = $this->createQueryBuilder('p')
            ->addorderBy('p.firstView', 'DESC')
            ->setMaxResults(400)
            ->getQuery();

        return $query->getResult();
    }

    function getAllCategories($category){
        $query = $this->createQueryBuilder('p')
            ->where('p.category LIKE :category')
            ->setParameter('category', $category)
            ->addorderBy('p.firstView', 'DESC')
            ->setMaxResults(400)
            ->getQuery();

        return $query->getResult();
    }

    function getAll2($label, $order){
        $query = $this->createQueryBuilder('p');
        if($label){
            $query->where('p.title LIKE :label')
                ->OrWhere('p.description LIKE :label')
                ->setParameter('label', '%'.$label.'%');
        }
        if($order=="price"){
            $query->addorderBy('p.price', 'DESC');
        } else {
            $query->addorderBy('p.firstView', 'DESC');

        }
        $res = $query->setMaxResults(400)
            ->getQuery()
            ->getResult();

        return $res;
    }

    function getBennes(){
        $query = $this->createQueryBuilder('p')
            ->where('p.price > 1000 and p.price < 10000 and (p.title LIKE :label or p.description LIKE :label or p.title LIKE :label2 or p.description LIKE :label2)')

            ->addorderBy('p.price', 'DESC')
            ->setMaxResults(400)
            ->setParameter('label', '%benne%')
            ->setParameter('label2', '%brimont%')
            ->getQuery();

        return $query->getResult();
    }


    function updateNew(){
        $res = $this->findByNew(true);
        $em = $this->getEntityManager();
        foreach($res as $r){
            $r->new = false;
            $em->persist($r);
        }
        $em->flush();

    }


    function saveOrUpdate($annonce, $mailer){
        $annonce->log = "";
        $annonce->new = true;

        $em = $this->getEntityManager();
        $annoncerepository = $this;
        $annonce2 = $annoncerepository->findOneByClientId($annonce->url);
        if($annonce2 == null){
            $annonce->firstView = $annonce->lastView;
            print("\n*******");
            print("\n*******");
            print("\nlink :   ".$annonce->url);
            print("\ntitle :  ".$annonce->title);
            print("\nprice :  ".$annonce->price);
            if($annonce->category == "immobilier_nantes"){
                $str = "";
                $str = $str."\nlink :   ".$annonce->url;
                $str = $str."\ntitle :   ".$annonce->title;
                $str = $str."\nprice :  ".$annonce->price;
                $from = "lemairec02@gmail.com";
                $to = "victorleonard@hotmail.fr";
                $message = (new \Swift_Message($str))->setSubject('Une nouvelle maison! vite')->setFrom($from)->setTo($to)->setBody($str);
                $res = $mailer->send($message);
                $res = mail($to, "$str", $str);
            }

            $em->persist($annonce);
            $em->flush();
            //print("\nimage :  ".$image);
            //print("\ntime :   ".$time);

            //print("\n*******\n");
            return true;
        } else {
            print("find annonce \n");
            $annonce2->lastView = new \DateTime();
            $em->persist($annonce2);
            $em->flush();
            return false;
        }
    }
}
