<?php

namespace App\Repository;
use App\Entity\Campagne;

/**
 * CampagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagneRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllforCompany($company){
        $query = $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->setParameter('company', $company)
            ->orderBy('p.name', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    function getAllAndNullforCompany($company){
        $res = $this->getAllforCompany($company);
        $res[] = null;

        return $res;
    }

    function findFirstOrCreate($company, $name){
        $em = $this->getEntityManager();
        $campagne = $this->findOneByCompany($company);
        if($campagne){
         return $campagne;
        }
        $campagne = new Campagne();
        $campagne->name = $name;
        $campagne->company = $company;
        $em->persist($campagne);
        $em->flush();
        return $campagne;
    }

    function findOrCreate($company, $name){
        $em = $this->getEntityManager();
        $campagne = $query = $this->createQueryBuilder('p')
         ->where('p.company = :company')
         ->andWhere('p.name = :name')
         ->setParameter('company', $company)
         ->setParameter('name', $name)
         ->getQuery()->getSingleResult();
        if($campagne){
         return $campagne;
        }
        $campagne = new Campagne();
        $campagne->name = $name;
        $campagne->company = $company;
        $em->persist($campagne);
        $em->flush();
        return $campagne;
    }
}
