<?php

namespace App\Repository;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForCampagne($campagne){
        return $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->orderBy('p.name')
            ->setParameter('company', $campagne->company)
            ->getQuery()->getResult();
    }

    function getAll(){
        return $this->createQueryBuilder('p')
            ->orderBy('p.name')
            ->getQuery()->getResult();
    }

    function getAllBanques(){
        return $this->createQueryBuilder('p')
            ->where("p.type = 'banque'")
            ->orderBy('p.name')
            ->getQuery()->getResult();
    }

    function getFirstBanque(){
        return $this->createQueryBuilder('p')
            ->where("p.type = 'banque'")
            ->orderBy('p.name')
            ->setMaxResults(1)->getQuery()->getOneOrNullResult();
    }

    function getNoBanques(){
        return $this->createQueryBuilder('p')
            ->where("p.type is null")
            ->orWhere("p.type != 'banque'")
            ->orderBy('p.name')
            ->getQuery()->getResult();
    }

    function getCompteTVA(){
        return $this->createQueryBuilder('p')
            ->where("p.type = 'tva'")
            ->orderBy('p.name')
            ->getQuery()->getResult()[0];
    }
}
