<?php

namespace App\Repository;
use App\Entity\Company;
use App\Entity\Campagne;
use App\Entity\Culture;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllForUser($user){
        $em = $this->getEntityManager();
        $companies = $this->createQueryBuilder('c')
            ->innerJoin('c.users', 'u')
            ->where('u.id = :user_id')
            ->orderBy('c.name')
            ->setParameter('user_id', $user->id)
            ->getQuery()->getResult();
        return $companies;
    }

    function findOrCreate($user){
        $companies = $this->getAllForUser($user);
        if(count($companies)>0){
            return $companies[0];
        }

        return $this->createCompany($user);
    }

    function createCompany($user){
        $company = new Company();
        $company->users = [$user];
        $company->name = $user->getUserName();
        $company->adresse = "";
        $company->site1_name = "";
        $company->site1_url = "";
        $em = $this->getEntityManager();
        $em->persist($company);
        $em->flush();

        $em = $this->getEntityManager();
        $em->getRepository(Campagne::class)->createCurrentCampagne($company);
        $em->getRepository(Culture::class)->createCurrentCulture($company);

        return $company;
    }
}
