<?php

namespace App\Repository;
use App\Entity\Culture;


/**
 * CultureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultureRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllforCompany($company){
        $query = $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->setParameter('company', $company)
            ->getQuery();

        return $query->getResult();
    }

    function findOrCreate($company, $name, $color = ""){
        $em = $this->getEntityManager();
        $culture = $query = $this->createQueryBuilder('p')
         ->where('p.company = :company')
         ->andWhere('p.name = :name')
         ->setParameter('company', $company)
         ->setParameter('name', $name)
         ->getQuery()->getOneOrNullResult();
        if($culture){
            return $culture;
        }
        $culture = new Culture();
        $culture->name = $name;
        $culture->company = $company;
        $em->persist($culture);
        $em->flush();
        return $culture;
    }

    function createCurrentCulture($company){
        $this->findOrCreate($company, "Blé", "");
    }
}
