<?php

namespace App\Repository;
use App\Entity\EphyPhraseRisque;

/**
 * EphyPhraseRisqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphyPhraseRisqueRepository extends \Doctrine\ORM\EntityRepository
{
    function get($name, $description){
        $em = $this->getEntityManager();
        $res = $this->find($name);
        if(!$res){
            $res = new EphyPhraseRisque();
            $res->id = $name;
            $res->description = $description;
            $res->cmr = false;
            $em->persist($res);
            $em->flush();
        }
        $res->description = $description;
        $em->persist($res);
        $em->flush();
        return $res;
    }
}
