<?php

namespace App\Repository;

/**
 * EphyUsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphyUsageRepository extends \Doctrine\ORM\EntityRepository
{
    function deleteForEphyProduit($ephyproduit){
        $em = $this->getEntityManager();
        $list = $this->findByEphyProduit($ephyproduit);
        foreach ($list as $l) {
            $em->remove($l);
        }
        $em->flush();
    }
}
