<?php

namespace App\Repository;

/**
 * EphyUsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphyUsageRepository extends \Doctrine\ORM\EntityRepository
{
    function deleteForEphyProduit($ephyproduit){
        $em = $this->getEntityManager();
        $list = $this->findByEphyProduit($ephyproduit);
        foreach ($list as $l) {
            $em->remove($l);
        }
        $em->flush();
    }
    public function findByEphyProduit($ephyProduit)
    {
        $res = $this->createQueryBuilder('m')
            ->andWhere('m.ephyProduit = :val')
            ->setParameter('val', $ephyProduit)
            ->orderBy('m.doseRetenu', 'DESC')
            ->getQuery()
            ->getResult()
        ;
        return $res;
    }
}
