<?php

namespace App\Repository;

/**
 * EphySubstanceProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EphySubstanceProduitRepository extends \Doctrine\ORM\EntityRepository
{
    function findByEphySubstance($ephy_substance){
        $query = $this->createQueryBuilder('p')
            ->join('p.ephyproduit', 'e')
            ->where('p.ephysubstance = :ephysubstance')
            ->andWhere('e.enable = true')
            ->orderBY('e.name')
            ->setParameter('ephysubstance', $ephy_substance)
            ->getQuery();

        return $query->getResult();
    }

    function deleteForEphyProduit($ephyproduit){
        $em = $this->getEntityManager();
        $list = $this->findByEphyproduit($ephyproduit);
        foreach ($list as $l) {
            $em->remove($l);
        }
        $em->flush();
    }
}
