<?php

namespace App\Repository;

use App\Entity\Ecriture;
use App\Entity\Operation;
/**
 * FactureFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    function save($facture){
        $em = $this->getEntityManager();

        $em->getRepository('App:Operation')->deleteForFacture($facture);

        $em->persist($facture);
        $em->flush();

        $operation = new Operation();
        $operation->name = $facture->name;
        $operation->date = $facture->date;
        $operation->facture = $facture;

        $em->persist($operation);
        $em->flush();

        $ecriture = new Ecriture();
        $ecriture->compte = $facture->banque;
        $ecriture->operation = $operation;
        $ecriture->value = $facture->montantTTC;
        $em->persist($ecriture);

        $ecriture = new Ecriture();
        $ecriture->compte = $facture->compte;
        $ecriture->operation = $operation;
        $ecriture->value = -$facture->montantHT;
        $ecriture->campagne = $facture->campagne;
        $em->persist($ecriture);

        if($facture->montantTTC!=$facture->montantHT){
            $ecriture = new Ecriture();
            $ecriture->compte = $em->getRepository('App:Compte')->getCompteTVA();
            $ecriture->operation = $operation;
            $ecriture->value = -($facture->montantTTC-$facture->montantHT);
            $em->persist($ecriture);
        }
        $em->flush();

    }

    function delete($facture){
        $em = $this->getEntityManager();

        $em->getRepository('App:Operation')->deleteForFacture($facture);
        $em->remove($facture);
        $em->flush();
    }

    function getAll(){
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.date', 'DESC')
            ->getQuery();

            return $query->getResult();
    }

    function selectLastDocument($facture_id){
        $query = $this->createQueryBuilder('p')
            ->select('p.brochure')
            ->where('p.id = :facture_id')
            ->setParameter('facture_id', $facture_id)
            ->setMaxResults(1)
            ->getQuery();
        $result = $query->getOneOrNullResult();
        if($result){
            return $result['brochure'];
        }
        return null;
    }

    function getAllForCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->orWhere('p.campagne is NULL')
            ->setParameter('campagne', $campagne)
            ->orderBy('p.date', 'DESC')
            ->getQuery();

            return $query->getResult();
    }
}
