<?php

namespace App\Repository;

/**
 * InterventionMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionMaterielRepository extends \Doctrine\ORM\EntityRepository
{
    function save($intervention_materiel){
        $em = $this->getEntityManager();
        $em->persist($intervention_materiel);
        $em->flush();
    }
}
