<?php

namespace App\Repository;

/**
 * MaterielEntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielEntretienRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByMateriel($value): array
    {
        return $this->createQueryBuilder('i')
            ->andWhere('i.materiel = :val')
            ->setParameter('val', $value)
            ->orderBy('i.date', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
