<?php

namespace App\Repository;
use App\Entity\Parcelle;

/**
 * ParcelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelleRepository extends \Doctrine\ORM\EntityRepository
{
    function save($parcelle){
        $em = $this->getEntityManager();
        $parcelle->completeName = $parcelle->getCultureName();
        if($parcelle->ilot){
            $parcelle->completeName = $parcelle->completeName." - ".$parcelle->getIlotName();
        }
        if($parcelle->name){
            $parcelle->completeName = $parcelle->completeName." - ".$parcelle->name;
        }
        $interventions =  $em->getRepository('App:Intervention')->getAllForParcelle($parcelle);
        foreach($interventions as $intervention){
            $em->getRepository('App:Intervention')->updateSurface($intervention->id);
        }
        $em->persist($parcelle);
        $em->flush();
        return $parcelle;

    }

    function getAllForCampagne($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->setParameter('campagne', $campagne)
            ->addorderBy('p.active', 'DESC')
            ->addorderBy('p.completeName', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    function getAllForCampagneWithoutActive($campagne){
        $query = $this->createQueryBuilder('p')
            ->where('p.campagne = :campagne')
            ->andWhere('p.active = true')
            ->setParameter('campagne', $campagne)
            ->addorderBy('p.active', 'DESC')
            ->addorderBy('p.completeName', 'ASC')
            ->getQuery();

        return $query->getResult();
    }


    function delete($parcelle_id){
        $em = $this->getEntityManager();
        $parcelle = $this->findOneById($parcelle_id);
        $em->remove($parcelle);
        $em->flush();
    }
}
