monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: buffered
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'contact@maplaine.fr'
            to_email:   'lemairec02@gmail.com'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject:    'An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
