monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: deduplicated
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        deduplicated:
            type:    deduplication
            handler: swift
