<?php

namespace App\Repository\Materiel;

/**
 * MaterielEntretienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielEntretienRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByMateriel($value): array
    {
        return $this->createQueryBuilder('i')
            ->andWhere('i.materiel = :val')
            ->setParameter('val', $value)
            ->orderBy('i.date', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function getLastEntretiens($value)
    {
        return $this->createQueryBuilder('i')
            ->andWhere('i.materiel = :val')
            ->andWhere('i.name != :val2')
            ->setParameter('val', $value)
            ->setParameter('val2', "inventaire")
            ->orderBy('i.date', 'DESC')
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
        ;
    }

    public function getLastInventaire($value)
    {
        return $this->createQueryBuilder('i')
            ->andWhere('i.materiel = :val')
            ->andWhere('i.name = :val2')
            ->setParameter('val', $value)
            ->setParameter('val2', "inventaire")
            ->orderBy('i.date', 'DESC')
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();
        ;
    }


    
}
