<?php

namespace App\Repository\Materiel;

/**
 * MaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllOkForCompany($company){
        return $this->createQueryBuilder('m')
            ->andWhere('m.company = :company')
            ->andWhere('m.dateVente is NULL')
            ->setParameter('company', $company)
            
            ->orderBy('m.type', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }

    function getAllKoForCompany($company){
        return $this->createQueryBuilder('m')
            ->andWhere('m.company = :company')
            ->andWhere('m.dateVente is not NULL')
            ->setParameter('company', $company)
            ->orderBy('m.type', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }

}
