<?php

namespace AnnonceBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    function getAll(){
        $query = $this->createQueryBuilder('p')
            ->addorderBy('p.firstView', 'DESC')
            ->setMaxResults(200)
            ->getQuery();

        return $query->getResult();
    }

    function getAll2($label){
        $query = $this->createQueryBuilder('p')
            ->where('p.title LIKE :label')
            ->OrWhere('p.description LIKE :label')
            ->addorderBy('p.firstView', 'DESC')
            ->setMaxResults(200)
            ->setParameter('label', '%'.$label.'%')
            ->getQuery();

        return $query->getResult();
    }
}
