<?php

namespace AnnonceBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    function getAll(){
        $query = $this->createQueryBuilder('p')
            ->addorderBy('p.firstView', 'DESC')
            ->setMaxResults(400)
            ->getQuery();

        return $query->getResult();
    }

    function getAll2($label){
        $query = $this->createQueryBuilder('p')
            ->where('p.title LIKE :label')
            ->OrWhere('p.description LIKE :label')
            ->addorderBy('p.firstView', 'DESC')
            ->setMaxResults(400)
            ->setParameter('label', '%'.$label.'%')
            ->getQuery();

        return $query->getResult();
    }

    function getBennes(){
        $query = $this->createQueryBuilder('p')
            ->where('p.price > 1000 and p.price < 10000 and (p.title LIKE :label or p.description LIKE :label or p.title LIKE :label2 or p.description LIKE :label2)')

            ->addorderBy('p.price', 'DESC')
            ->setMaxResults(400)
            ->setParameter('label', '%benne%')
            ->setParameter('label2', '%brimont%')
            ->getQuery();

        return $query->getResult();
    }


    function updateNew(){
        $res = $this->findByNew(true);
        $em = $this->getEntityManager();
        foreach($res as $r){
            $r->new = false;
            $em->persist($r);
        }
        $em->flush();

    }


    function saveOrUpdate($annonce){
        $annonce->log = "";
        $annonce->new = true;
        
        $em = $this->getEntityManager();
        $annoncerepository = $this;
        $annonce2 = $annoncerepository->findOneByClientId($annonce->url);
        if($annonce2 == null){
            $annonce->firstView = $annonce->lastView;
            print("\n*******");
            print("\n*******");
            print("\nlink :   ".$annonce->url);
            print("\ntitle :  ".$annonce->title);
            print("\nprice :  ".$annonce->price);
            $em->persist($annonce);
            $em->flush();
            //print("\nimage :  ".$image);
            //print("\ntime :   ".$time);

            //print("\n*******\n");
            return true;
        } else {
            print("find annonce \n");
            $annonce2->lastView = $annonce->lastView;
            $em->persist($annonce2);
            $em->flush();
            return false;
        }
    }
}
